import { useCountryData } from "../../hooks/useCountryData";

const options = [
    { value: "af", label: "Afghanistan" },
    { value: "al", label: "Albania" },
    { value: "dz", label: "Algeria" },
    { value: "as", label: "American Samoa" },
    { value: "ad", label: "Andorra" },
    { value: "ao", label: "Angola" },
    { value: "ag", label: "Antigua and Barbuda" },
    { value: "ar", label: "Argentina" },
    { value: "am", label: "Armenia" },
    { value: "aw", label: "Aruba" },
    { value: "au", label: "Australia" },
    { value: "at", label: "Austria" },
    { value: "az", label: "Azerbaijan" },
    { value: "bs", label: "Bahamas, The" },
    { value: "bh", label: "Bahrain" },
    { value: "bd", label: "Bangladesh" },
    { value: "bb", label: "Barbados" },
    { value: "by", label: "Belarus" },
    { value: "be", label: "Belgium" },
    { value: "bz", label: "Belize" },
    { value: "bj", label: "Benin" },
    { value: "bm", label: "Bermuda" },
    { value: "bt", label: "Bhutan" },
    { value: "bo", label: "Bolivia" },
    { value: "ba", label: "Bosnia and Herzegovina" },
    { value: "bw", label: "Botswana" },
    { value: "br", label: "Brazil" },
    { value: "vg", label: "British Virgin Islands" },
    { value: "bn", label: "Brunei Darussalam" },
    { value: "bg", label: "Bulgaria" },
    { value: "bf", label: "Burkina Faso" },
    { value: "bi", label: "Burundi" },
    { value: "cv", label: "Cabo Verde" },
    { value: "kh", label: "Cambodia" },
    { value: "cm", label: "Cameroon" },
    { value: "ca", label: "Canada" },
    { value: "ky", label: "Cayman Islands" },
    { value: "cf", label: "Central African Republic" },
    { value: "td", label: "Chad" },
    { value: "cl", label: "Chile" },
    { value: "cn", label: "China" },
    { value: "co", label: "Colombia" },
    { value: "km", label: "Comoros" },
    { value: "cd", label: "Congo, Dem. Rep." },
    { value: "cg", label: "Congo, Rep." },
    { value: "cr", label: "Costa Rica" },
    { value: "ci", label: "Cote d'Ivoire" },
    { value: "hr", label: "Croatia" },
    { value: "cu", label: "Cuba" },
    { value: "cw", label: "Curacao" },
    { value: "cy", label: "Cyprus" },
    { value: "cz", label: "Czechia" },
    { value: "dk", label: "Denmark" },
    { value: "dj", label: "Djibouti" },
    { value: "dm", label: "Dominica" },
    { value: "do", label: "Dominican Republic" },
    { value: "ec", label: "Ecuador" },
    { value: "eg", label: "Egypt, Arab Rep." },
    { value: "sv", label: "El Salvador" },
    { value: "gq", label: "Equatorial Guinea" },
    { value: "er", label: "Eritrea" },
    { value: "ee", label: "Estonia" },
    { value: "sz", label: "Eswatini" },
    { value: "et", label: "Ethiopia" },
    { value: "fo", label: "Faroe Islands" },
    { value: "fj", label: "Fiji" },
    { value: "fi", label: "Finland" },
    { value: "fr", label: "France" },
    { value: "pf", label: "French Polynesia" },
    { value: "ga", label: "Gabon" },
    { value: "gm", label: "Gambia, The" },
    { value: "ge", label: "Georgia" },
    { value: "de", label: "Germany" },
    { value: "gh", label: "Ghana" },
    { value: "gi", label: "Gibraltar" },
    { value: "gr", label: "Greece" },
    { value: "gl", label: "Greenland" },
    { value: "gd", label: "Grenada" },
    { value: "gu", label: "Guam" },
    { value: "gt", label: "Guatemala" },
    { value: "gn", label: "Guinea" },
    { value: "gw", label: "Guinea-Bissau" },
    { value: "gy", label: "Guyana" },
    { value: "ht", label: "Haiti" },
    { value: "hn", label: "Honduras" },
    { value: "hk", label: "Hong Kong SAR, China" },
    { value: "hu", label: "Hungary" },
    { value: "is", label: "Iceland" },
    { value: "in", label: "India" },
    { value: "id", label: "Indonesia" },
    { value: "ir", label: "Iran, Islamic Rep." },
    { value: "iq", label: "Iraq" },
    { value: "ie", label: "Ireland" },
    { value: "im", label: "Isle of Man" },
    { value: "il", label: "Israel" },
    { value: "it", label: "Italy" },
    { value: "jm", label: "Jamaica" },
    { value: "jp", label: "Japan" },
    { value: "jo", label: "Jordan" },
    { value: "kz", label: "Kazakhstan" },
    { value: "ke", label: "Kenya" },
    { value: "ki", label: "Kiribati" },
    { value: "kp", label: "Korea, Dem. People's Rep." },
    { value: "kr", label: "Korea, Rep." },
    { value: "xk", label: "Kosovo" },
    { value: "kw", label: "Kuwait" },
    { value: "kg", label: "Kyrgyz Republic" },
    { value: "la", label: "Lao PDR" },
    { value: "lv", label: "Latvia" },
    { value: "lb", label: "Lebanon" },
    { value: "ls", label: "Lesotho" },
    { value: "lr", label: "Liberia" },
    { value: "ly", label: "Libya" },
    { value: "li", label: "Liechtenstein" },
    { value: "lt", label: "Lithuania" },
    { value: "lu", label: "Luxembourg" },
    { value: "mo", label: "Macao SAR, China" },
    { value: "mg", label: "Madagascar" },
    { value: "mw", label: "Malawi" },
    { value: "my", label: "Malaysia" },
    { value: "mv", label: "Maldives" },
    { value: "ml", label: "Mali" },
    { value: "mt", label: "Malta" },
    { value: "mh", label: "Marshall Islands" },
    { value: "mr", label: "Mauritania" },
    { value: "mu", label: "Mauritius" },
    { value: "mx", label: "Mexico" },
    { value: "fm", label: "Micronesia, Fed. Sts." },
    { value: "md", label: "Moldova" },
    { value: "mc", label: "Monaco" },
    { value: "mn", label: "Mongolia" },
    { value: "me", label: "Montenegro" },
    { value: "ma", label: "Morocco" },
    { value: "mz", label: "Mozambique" },
    { value: "mm", label: "Myanmar" },
    { value: "na", label: "Namibia" },
    { value: "nr", label: "Nauru" },
    { value: "np", label: "Nepal" },
    { value: "nl", label: "Netherlands" },
    { value: "nc", label: "New Caledonia" },
    { value: "nz", label: "New Zealand" },
    { value: "ni", label: "Nicaragua" },
    { value: "ne", label: "Niger" },
    { value: "ng", label: "Nigeria" },
    { value: "mk", label: "North Macedonia" },
    { value: "mp", label: "Northern Mariana Islands" },
    { value: "no", label: "Norway" },
    { value: "om", label: "Oman" },
    { value: "pk", label: "Pakistan" },
    { value: "pw", label: "Palau" },
    { value: "pa", label: "Panama" },
    { value: "pg", label: "Papua New Guinea" },
    { value: "py", label: "Paraguay" },
    { value: "pe", label: "Peru" },
    { value: "ph", label: "Philippines" },
    { value: "pl", label: "Poland" },
    { value: "pt", label: "Portugal" },
    { value: "pr", label: "Puerto Rico" },
    { value: "qa", label: "Qatar" },
    { value: "ro", label: "Romania" },
    { value: "ru", label: "Russian Federation" },
    { value: "rw", label: "Rwanda" },
    { value: "ws", label: "Samoa" },
    { value: "sm", label: "San Marino" },
    { value: "st", label: "Sao Tome and Principe" },
    { value: "sa", label: "Saudi Arabia" },
    { value: "sn", label: "Senegal" },
    { value: "rs", label: "Serbia" },
    { value: "sc", label: "Seychelles" },
    { value: "sl", label: "Sierra Leone" },
    { value: "sg", label: "Singapore" },
    { value: "sx", label: "Sint Maarten (Dutch part)" },
    { value: "sk", label: "Slovak Republic" },
    { value: "si", label: "Slovenia" },
    { value: "sb", label: "Solomon Islands" },
    { value: "so", label: "Somalia" },
    { value: "za", label: "South Africa" },
    { value: "ss", label: "South Sudan" },
    { value: "es", label: "Spain" },
    { value: "lk", label: "Sri Lanka" },
    { value: "kn", label: "St. Kitts and Nevis" },
    { value: "lc", label: "St. Lucia" },
    { value: "mf", label: "St. Martin (French part)" },
    { value: "vc", label: "St. Vincent and the Grenadines" },
    { value: "sd", label: "Sudan" },
    { value: "sr", label: "Suriname" },
    { value: "se", label: "Sweden" },
    { value: "ch", label: "Switzerland" },
    { value: "sy", label: "Syrian Arab Republic" },
    { value: "tw", label: "Taiwan, China" },
    { value: "tj", label: "Tajikistan" },
    { value: "tz", label: "Tanzania" },
    { value: "th", label: "Thailand" },
    { value: "tl", label: "Timor-Leste" },
    { value: "tg", label: "Togo" },
    { value: "to", label: "Tonga" },
    { value: "tt", label: "Trinidad and Tobago" },
    { value: "tn", label: "Tunisia" },
    { value: "tr", label: "Türkiye" },
    { value: "tm", label: "Turkmenistan" },
    { value: "tc", label: "Turks and Caicos Islands" },
    { value: "tv", label: "Tuvalu" },
    { value: "ug", label: "Uganda" },
    { value: "ua", label: "Ukraine" },
    { value: "ae", label: "United Arab Emirates" },
    { value: "gb", label: "United Kingdom" },
    { value: "us", label: "United States" },
    { value: "uy", label: "Uruguay" },
    { value: "uz", label: "Uzbekistan" },
    { value: "vu", label: "Vanuatu" },
    { value: "ve", label: "Venezuela, RB" },
    { value: "vn", label: "Vietnam" },
    { value: "vi", label: "Virgin Islands (U.S.)" },
    { value: "ps", label: "West Bank and Gaza" },
    { value: "ye", label: "Yemen, Rep." },
    { value: "zm", label: "Zambia" },
    { value: "zw", label: "Zimbabwe" }
];


function CountrySelection() {
    const { country, switchCountry } = useCountryData()

    return (
        <select
            value={country}
            onChange={(e) => switchCountry(e.target.value)}
        >
            {options.map((opt) => (
                <option key={opt.value} value={opt.value}>
                    {opt.label}
                </option>
            ))}
        </select>
    );
}

export default CountrySelection;